report_an_issue:
  name: Send problem report
  description: Send a report about any problem with your Smart Home
  fields:
    only_description:
      description: True for repeated errors
      name: Only Description
      required: true
      selector:
        boolean:
    description:
      description: Describe your problem
      name: Description
      required: true
      selector:
        text:
    mail:
      description: E-mail address to contact you
      name: E-mail 
      required: true
      selector:
        text:
    phone_number:
      description: Phone number to contact you (Optional)
      name: Phone Number
      required: false
      selector: 
        text:
    picture:
      description: You can attach the photo or screenshot to illustrate the problem
      name: Picture
      required: false
      selector:
        text: